---
- name: Install Packages
  hosts: "{{  Target }}"
  gather_facts: no
  become: yes
  tasks:
# 1. Install Packages
    - name: Yum Install
      vars:
        ansible_become: yes
        ansible_become_method: sudo
        ansible_become_user: root
      "{{ Name }}":
        name: "{{ Name }}"
        state: latest


